In [6]:
import pandas as pd
import numpy as np

df_transacciones=pd.read_csv("../data/clean/features/hey_transacciones_features_limpio.csv")

df_transacciones.head()

,user_id,total_transacciones,monto_total,monto_promedio,monto_maximo,transacciones_completadas,transacciones_no_procesadas,transacciones_en_disputa,transacciones_revertidas,operaciones_internacionales,...,tasa_reversos,tasa_internacional,dias_desde_ultima_transaccion,variacion_actividad,score_riesgo_transaccional,score_oportunidad_transaccional,nivel_riesgo_transaccional,nivel_oportunidad_transaccional,insight_transaccional,es_usuario_atipico
0,USR-00001,56,119570.59,2135.189107,24010.0,53,3,0,0,2,...,0.000000,0.035714,23,-0.600000,20,75,Bajo,Alto,Cliente activo y con alto potencial comercial....,0
1,USR-00002,74,212722.67,2874.630676,24830.0,71,1,1,1,1,...,0.013514,0.013514,18,-0.500000,20,75,Bajo,Alto,Cliente activo y con alto potencial comercial....,0
2,USR-00003,79,190801.09,2415.203671,24540.0,71,4,3,1,4,...,0.012658,0.050633,20,-0.700000,40,75,Medio,Alto,Cliente activo y con alto potencial comercial....,0
3,USR-00004,66,580113.74,8789.602121,55000.0,61,2,2,1,2,...,0.015152,0.030303,19,-0.333333,20,90,Bajo,Alto,Cliente activo y con alto potencial comercial....,0
4,USR-00005,93,190277.30,2045.992473,24520.0,89,2,2,0,1,...,0.000000,0.010753,29,-0.916667,20,75,Bajo,Alto,Cliente activo y con alto potencial comercial....,0

In [7]:
df_transacciones.info()

<class 'pandas.DataFrame'>
RangeIndex: 15025 entries, 0 to 15024
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   user_id                          15025 non-null  str
 1   total_transacciones              15025 non-null  int64
 2   monto_total                      15025 non-null  float64
 3   monto_promedio                   15025 non-null  float64
 4   monto_maximo                     15025 non-null  float64
 5   transacciones_completadas        15025 non-null  int64
 6   transacciones_no_procesadas      15025 non-null  int64
 7   transacciones_en_disputa         15025 non-null  int64
 8   transacciones_revertidas         15025 non-null  int64
 9   operaciones_internacionales      15025 non-null  int64
 10  operaciones_atipicas             15025 non-null  int64
 11  cashback_total                   15025 non-null  float64
 12  meses_diferidos_promedio         15025 non-null  float64
 13  ultima_transaccion               15025 non-null  str
 14  primera_transaccion              15025 non-null  str
 15  canal_principal                  15025 non-null  str
 16  dispositivo_principal            15025 non-null  str
 17  tipo_operacion_principal         15025 non-null  str
 18  ciudad_principal                 15025 non-null  str
 19  categoria_principal              15025 non-null  str
 20  canales_usados                   15025 non-null  int64
 21  productos_usados                 15025 non-null  int64
 22  comercios_usados                 15025 non-null  int64
 23  tipos_operacion_usados           15025 non-null  int64
 24  transacciones_ultimos_30_dias    15025 non-null  int64
 25  transacciones_previos_30_dias    15025 non-null  int64
 26  tasa_no_procesadas               15025 non-null  float64
 27  tasa_disputas                    15025 non-null  float64
 28  tasa_reversos                    15025 non-null  float64
 29  tasa_internacional               15025 non-null  float64
 30  dias_desde_ultima_transaccion    15025 non-null  int64
 31  variacion_actividad              15025 non-null  float64
 32  score_riesgo_transaccional       15025 non-null  int64
 33  score_oportunidad_transaccional  15025 non-null  int64
 34  nivel_riesgo_transaccional       15025 non-null  str
 35  nivel_oportunidad_transaccional  15025 non-null  str
 36  insight_transaccional            15025 non-null  str
 37  es_usuario_atipico               15025 non-null  int64
dtypes: float64(10), int64(17), str(11)
memory usage: 4.4 MB

In [8]:
df_clientes=pd.read_csv("../data/clean/features/hey_clientes_features_limpio.csv")

df_clientes.head()

,user_id,edad,sexo,estado,ciudad,nivel_educativo,ocupacion,ingreso_mensual_mxn,antiguedad_dias,es_hey_pro,...,score_buro,dias_desde_ultimo_login,preferencia_canal,satisfaccion_1_10,recibe_remesas,usa_hey_shop,idioma_preferido,tiene_seguro,num_productos_activos,patron_uso_atipico
0,USR-00001,21,M,Ciudad de México,CDMX - Benito Juárez,Preparatoria,Empleado,24500,1554,True,...,527,1,app_android,10.0,False,True,es_MX,False,2,False
1,USR-00002,18,M,Jalisco,Puerto Vallarta,Preparatoria,Estudiante,19000,1410,True,...,714,3,app_android,8.0,False,True,es_MX,True,2,False
2,USR-00003,23,H,Chihuahua,Cuauhtémoc,Licenciatura,Estudiante,14000,1174,True,...,454,3,app_ios,8.0,False,True,es_MX,False,2,False
3,USR-00004,32,SE,Nuevo León,Guadalupe,Posgrado,Empleado,61000,1168,False,...,837,16,app_ios,10.0,True,False,es_MX,True,3,False
4,USR-00005,26,M,Ciudad de México,CDMX - Cuauhtémoc,Preparatoria,Empresario,27000,816,True,...,533,1,app_ios,7.0,False,True,es_MX,True,2,False

In [9]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 15025 entries, 0 to 15024
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  15025 non-null  str
 1   edad                     15025 non-null  int64
 2   sexo                     15025 non-null  str
 3   estado                   15025 non-null  str
 4   ciudad                   15025 non-null  str
 5   nivel_educativo          15025 non-null  str
 6   ocupacion                15025 non-null  str
 7   ingreso_mensual_mxn      15025 non-null  int64
 8   antiguedad_dias          15025 non-null  int64
 9   es_hey_pro               15025 non-null  bool
 10  nomina_domiciliada       15025 non-null  bool
 11  canal_apertura           15025 non-null  str
 12  score_buro               15025 non-null  int64
 13  dias_desde_ultimo_login  15025 non-null  int64
 14  preferencia_canal        15025 non-null  str
 15  satisfaccion_1_10        15025 non-null  float64
 16  recibe_remesas           15025 non-null  bool
 17  usa_hey_shop             15025 non-null  bool
 18  idioma_preferido         15025 non-null  str
 19  tiene_seguro             15025 non-null  bool
 20  num_productos_activos    15025 non-null  int64
 21  patron_uso_atipico       15025 non-null  bool
dtypes: bool(6), float64(1), int64(6), str(9)
memory usage: 1.9 MB

In [10]:
df_productos=pd.read_csv("../data/clean/features/hey_productos_features_limpio.csv")

df_productos.head()

,user_id,total_productos,productos_activos,productos_cancelados,productos_suspendidos,productos_en_revision,total_creditos,total_tarjetas,total_seguros,total_cuentas,total_inversiones,limite_credito_total,saldo_total_productos,utilizacion_promedio,tasa_interes_promedio,mensualidad_total,producto_principal,estatus_principal,fecha_producto_mas_reciente,fecha_ultimo_movimiento_producto
0,USR-00001,2,2,0,0,0,1,1,0,1,0,144000.0,169745.00,0.308300,17.855,0.0,cuenta_debito,activo,2023-06-26,2025-11-27
1,USR-00002,2,2,0,0,0,1,1,0,1,0,22000.0,26835.14,0.139150,17.040,0.0,cuenta_debito,activo,2025-07-18,2025-10-16
2,USR-00003,2,2,0,0,0,1,1,0,1,0,5000.0,5000.15,0.154550,19.940,0.0,cuenta_debito,activo,2024-04-24,2025-10-15
3,USR-00004,3,3,0,0,0,1,1,0,1,1,67000.0,357230.61,0.117933,15.630,0.0,cuenta_debito,activo,2024-06-19,2025-11-08
4,USR-00005,2,2,0,0,0,1,1,0,1,0,136000.0,129359.71,0.316300,15.475,0.0,cuenta_debito,activo,2025-04-02,2025-11-21

In [12]:
df_productos.info()

<class 'pandas.DataFrame'>
RangeIndex: 15025 entries, 0 to 15024
Data columns (total 20 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15025 non-null  str
 1   total_productos                   15025 non-null  int64
 2   productos_activos                 15025 non-null  int64
 3   productos_cancelados              15025 non-null  int64
 4   productos_suspendidos             15025 non-null  int64
 5   productos_en_revision             15025 non-null  int64
 6   total_creditos                    15025 non-null  int64
 7   total_tarjetas                    15025 non-null  int64
 8   total_seguros                     15025 non-null  int64
 9   total_cuentas                     15025 non-null  int64
 10  total_inversiones                 15025 non-null  int64
 11  limite_credito_total              15025 non-null  float64
 12  saldo_total_productos             15025 non-null  float64
 13  utilizacion_promedio              15025 non-null  float64
 14  tasa_interes_promedio             15025 non-null  float64
 15  mensualidad_total                 15025 non-null  float64
 16  producto_principal                15025 non-null  str
 17  estatus_principal                 15025 non-null  str
 18  fecha_producto_mas_reciente       15025 non-null  str
 19  fecha_ultimo_movimiento_producto  15025 non-null  str
dtypes: float64(5), int64(10), str(5)
memory usage: 2.3 MB

In [13]:
# Verificamos que no haya duplicados en la llave primaria
assert df_clientes['user_id'].is_unique, "¡Alerta! Hay user_id duplicados en Clientes"
assert df_transacciones['user_id'].is_unique, "¡Alerta! Hay user_id duplicados en Transacciones"
assert df_productos['user_id'].is_unique, "¡Alerta! Hay user_id duplicados en Productos"

In [14]:
# 1. Unir Clientes con Productos
df_intermedio = pd.merge(df_clientes, df_productos, on='user_id', how='inner')

# 2. Unir el resultado con Transacciones
df_master = pd.merge(df_intermedio, df_transacciones, on='user_id', how='inner')

# 3. Comprobación final
print(f"Dimensiones de la matriz final: {df_master.shape}")

Dimensiones de la matriz final: (15025, 78)

In [15]:
ruta_salida = "../data/clean/features/hey_merge_features_limpio.csv"

df_master.to_csv(ruta_salida, index=False, encoding="utf-8-sig")

print(f"✅ Proceso completado. Archivo guardado en: {ruta_salida}")

✅ Proceso completado. Archivo guardado en: ../data/clean/features/hey_merge_features_limpio.csv