In [15]:
import pandas as pd
import numpy as np

df=pd.read_csv("../data/raw/dataset_transacciones/hey_transacciones.csv")

df.head()

,transaccion_id,user_id,producto_id,fecha_hora,tipo_operacion,canal,monto,comercio_nombre,categoria_mcc,ciudad_transaccion,...,intento_numero,meses_diferidos,cashback_generado,descripcion_libre,hora_del_dia,dia_semana,es_internacional,dispositivo,patron_uso_atipico,es_dato_sintetico
0,TXN-0000000055,USR-00001,PRD-00000002,2025-01-15 14:17:42,compra,app_ios,33.88,DivertidoPark,entretenimiento,"Nueva York, NY",...,1,NaN,0.34,Cargo automático,14,Wednesday,True,app_ios,False,True
1,TXN-0000000048,USR-00001,PRD-00000001,2025-01-17 00:31:56,cargo_recurrente,app_ios,249.00,GamerPass,servicios_digitales,CDMX - Benito Juárez,...,1,NaN,NaN,Cargo automático,0,Friday,False,app_ios,False,True
2,TXN-0000000018,USR-00001,PRD-00000001,2025-01-17 22:48:23,cargo_recurrente,app_huawei,399.00,CloudDrive MX,servicios_digitales,CDMX - Benito Juárez,...,1,NaN,NaN,inv hey,22,Friday,False,app_huawei,False,True
3,TXN-0000000043,USR-00001,PRD-00000001,2025-01-19 11:10:43,transf_salida,app_android,8910.00,NaN,transferencia,CDMX - Benito Juárez,...,1,NaN,NaN,SPEI enviado,11,Sunday,False,app_android,False,True
4,TXN-0000000009,USR-00001,PRD-00000001,2025-02-15 07:03:50,compra,app_ios,568.59,QuickBite MX,restaurante,CDMX - Benito Juárez,...,1,NaN,5.69,dep. efvo,7,Saturday,False,app_ios,False,True

In [16]:
df.columns

Index(['transaccion_id', 'user_id', 'producto_id', 'fecha_hora',
       'tipo_operacion', 'canal', 'monto', 'comercio_nombre', 'categoria_mcc',
       'ciudad_transaccion', 'estatus', 'motivo_no_procesada',
       'intento_numero', 'meses_diferidos', 'cashback_generado',
       'descripcion_libre', 'hora_del_dia', 'dia_semana', 'es_internacional',
       'dispositivo', 'patron_uso_atipico', 'es_dato_sintetico'],
      dtype='str')

In [17]:
df.shape

(802384, 22)

In [18]:
df["fecha_hora"] = pd.to_datetime(df["fecha_hora"], errors="coerce")

df["monto"] = pd.to_numeric(df["monto"], errors="coerce").fillna(0)

df["cashback_generado"] = pd.to_numeric(df["cashback_generado"], errors="coerce").fillna(0)

df["meses_diferidos"] = pd.to_numeric(df["meses_diferidos"], errors="coerce").fillna(0)

df["motivo_no_procesada"] = df["motivo_no_procesada"].fillna("sin_motivo")
df["comercio_nombre"] = df["comercio_nombre"].fillna("sin_comercio")
df["descripcion_libre"] = df["descripcion_libre"].fillna("sin_descripcion")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 802384 entries, 0 to 802383
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaccion_id       802384 non-null  str
 1   user_id              802384 non-null  str
 2   producto_id          802384 non-null  str
 3   fecha_hora           802384 non-null  datetime64[us]
 4   tipo_operacion       802384 non-null  str
 5   canal                802384 non-null  str
 6   monto                802384 non-null  float64
 7   comercio_nombre      802384 non-null  str
 8   categoria_mcc        802384 non-null  str
 9   ciudad_transaccion   783117 non-null  str
 10  estatus              802384 non-null  str
 11  motivo_no_procesada  802384 non-null  str
 12  intento_numero       802384 non-null  int64
 13  meses_diferidos      802384 non-null  float64
 14  cashback_generado    802384 non-null  float64
 15  descripcion_libre    802384 non-null  str
 16  hora_del_dia         802384 non-null  int64
 17  dia_semana           802384 non-null  str
 18  es_internacional     802384 non-null  bool
 19  dispositivo          600321 non-null  str
 20  patron_uso_atipico   802384 non-null  bool
 21  es_dato_sintetico    802384 non-null  bool
dtypes: bool(3), datetime64[us](1), float64(3), int64(2), str(13)
memory usage: 118.6 MB

In [19]:
df["es_completada"] = (df["estatus"] == "completada").astype(int)
df["es_no_procesada"] = (df["estatus"] == "no_procesada").astype(int)
df["es_disputa"] = (df["estatus"] == "en_disputa").astype(int)
df["es_revertida"] = (df["estatus"] == "revertida").astype(int)

df["es_internacional_num"] = df["es_internacional"].astype(int)
df["es_atipica_num"] = df["patron_uso_atipico"].astype(int)

df.head()

,transaccion_id,user_id,producto_id,fecha_hora,tipo_operacion,canal,monto,comercio_nombre,categoria_mcc,ciudad_transaccion,...,es_internacional,dispositivo,patron_uso_atipico,es_dato_sintetico,es_completada,es_no_procesada,es_disputa,es_revertida,es_internacional_num,es_atipica_num
0,TXN-0000000055,USR-00001,PRD-00000002,2025-01-15 14:17:42,compra,app_ios,33.88,DivertidoPark,entretenimiento,"Nueva York, NY",...,True,app_ios,False,True,1,0,0,0,1,0
1,TXN-0000000048,USR-00001,PRD-00000001,2025-01-17 00:31:56,cargo_recurrente,app_ios,249.00,GamerPass,servicios_digitales,CDMX - Benito Juárez,...,False,app_ios,False,True,1,0,0,0,0,0
2,TXN-0000000018,USR-00001,PRD-00000001,2025-01-17 22:48:23,cargo_recurrente,app_huawei,399.00,CloudDrive MX,servicios_digitales,CDMX - Benito Juárez,...,False,app_huawei,False,True,1,0,0,0,0,0
3,TXN-0000000043,USR-00001,PRD-00000001,2025-01-19 11:10:43,transf_salida,app_android,8910.00,sin_comercio,transferencia,CDMX - Benito Juárez,...,False,app_android,False,True,1,0,0,0,0,0
4,TXN-0000000009,USR-00001,PRD-00000001,2025-02-15 07:03:50,compra,app_ios,568.59,QuickBite MX,restaurante,CDMX - Benito Juárez,...,False,app_ios,False,True,1,0,0,0,0,0

In [20]:
fecha_ref = df["fecha_hora"].max()

inicio_ultimos_30 = fecha_ref - pd.Timedelta(days=30)
inicio_previos_30 = fecha_ref - pd.Timedelta(days=60)

df["en_ultimos_30"] = (df["fecha_hora"] >= inicio_ultimos_30).astype(int)

df["en_previos_30"] = (
    (df["fecha_hora"] >= inicio_previos_30) &
    (df["fecha_hora"] < inicio_ultimos_30)
).astype(int)

fecha_ref

Timestamp('2025-12-15 13:59:36')

In [21]:
ruta_salida = "../data/clean/hey_transacciones_limpia.csv"

df.to_csv(ruta_salida, index=False, encoding="utf-8-sig")

print(f"✅ Proceso completado. Archivo guardado en: {ruta_salida}")

✅ Proceso completado. Archivo guardado en: ../data/clean/hey_transacciones_limpia.csv